spring:
  application:
    name: kan
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: true
    # 下面为连接池的补充设置，应用到上面所有数据源中
    hikari:
      time-between-eviction-runs-millis: 18800 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      default-auto-commit: true #自动提交
      auto-commit: true #指定updates是否自动提交
      idle-timeout: 30000 #<!-- 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟 -->
      pool-name: DatebookHikariCP #mssHikariCP
      max-lifetime: 1800000
      connection-timeout: 60000 #<!-- 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒 -->
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: select 1
  redis:
    #    host: 127.0.0.1
    host: 172.16.10.156
    #    password:
    password: kanshunfu
    port: 6379
    database: 0
    timeout: 300000
    #    cluster:
    #      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385
    #      max-redirects: 3
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 20 # 连接池中的最大空闲连接 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 20 # 连接池中的最小空闲连接 默认 0